### ISSUE TITLE
Map not loading in China

### ISSUE THREAD

**Issue by classaction** [weiweicui/PowerBI-Routemap#15]
![china_map](https://user-images.githubusercontent.com/6367907/62918297-ce643900-bdd1-11e9-8613-6e03cb84b5ba.png)

In china, the background map does not load. 
Microsoft have fixed this recently (May-June 2019) for their own visual. Any chance to apply that fix here too?

**Comment by classaction** [comment]
Hi, it's been 7 days without reply. Is this the right channel?
If yes, do you need more information?

**Comment by 2000mdc** [comment]
Me2! The same question.
@weiweicui Is it blocked by gov or just issue with ms bi function loading?

**Comment by 2000mdc** [comment]
> Hi, it's been 7 days without reply. Is this the right channel?
> If yes, do you need more information?

@classaction you need to download this repository, and manually load the power bi customer visual template in dist folder 1.4.2 version

**Comment by 2000mdc** [comment]
> Me2! The same question.
> @weiweicui Is it blocked by gov or just issue with ms bi function loading?

@weiweicui  It's not the updated version in the MS BI app store. When it's imported, it could not show the map loads in China.

**Comment by classaction** [comment]
I had a long conversation with Microsoft and @weiweicui  about this. In the end yes I believe a new dist version solved it.
