### ISSUE TITLE
Line is drawn incorrectly when crossing the antimeridian

### ISSUE THREAD

**Issue by robrien6** [weiweicui/PowerBI-Routemap#2]
When Crossing the antimeridian on a route (eg when the longitude value goes from -179.99 to 179.99) the line is not drawn based on the shortest route and instead wraps around the world.

The enclosed PBIX file shows this for Taxi 2, this becomes a problem when shown flight paths, vessel tracks etc.

The problem is better described here:  https://www.gearthblog.com/blog/archives/2015/08/crossing-the-antimeridian-in-google-earth.html 
[Problem crossing the antimeridian.zip](https://github.com/weiweicui/PowerBI-Routemap/files/1082069/Problem.crossing.the.antimeridian.zip)

Is there a way to force it to take the shortest route rather than circling the globe?

**Comment by weiweicui** [comment]
Thanks for the feedback. This is a little tricky. I have not found an official solution yet. But make a quick patch in 1.1.4. Probably working for many cases :)
