### ISSUE TITLE
Adding + & - buttons for zoom out and zoom in

### ISSUE THREAD

**Issue by hamza005** [weiweicui/PowerBI-Routemap#8]
Hello everyone here! I want to add (+) & (-) buttons in Route Map for zoom in and zoom out like in google maps etc. Is it possible in Power BI custom Route Map? If yes, then what's the procedure? Thank you everyone in advance.

**Comment by weiweicui** [comment]
So far it not supported, but should be easy to add.

**Comment by hamza005** [comment]
I'll be very thankful to you if you add it in the very next update.

**Comment by hamza005** [comment]
I've added the buttons into the svg element but unable to add the zoom functionality to them. Because of the different coding practices. can you help me out? Here is the screen shot of code and visual:

![screenshot 22](https://user-images.githubusercontent.com/20417498/37767126-d14acd96-2dea-11e8-879c-434824a38908.png)
![screenshot 23](https://user-images.githubusercontent.com/20417498/37767127-d17f242e-2dea-11e8-9ae0-faf135351df1.png)

**Comment by weiweicui** [comment]
well, i think you do not need to make your own buttons. if you do not mind using default controls, there should be initial settings you can use i guess? you can check bingmap apis.

**Comment by hamza005** [comment]
okay i'll check them. What if u add my desired functionality in the heat map. I'm doing this all for heat map. so if it possible for you so...

**Comment by hamza005** [comment]
Thank you so much. It was easy. done!
