### ISSUE TITLE
Code not working in Power BI web

### ISSUE THREAD

**Issue by hamza005** [weiweicui/PowerBI-Routemap#9]
Hello! I downloaded the code and followed the instructions. Every thing is running nicely... Following image is of the terminal after running 

> npm run watch

![screenshot 13](https://user-images.githubusercontent.com/20417498/37650366-8b536446-2c56-11e8-9369-f3c609e64dfb.png)

But the visual on the power BI web is empty... following is the screen shot of the web visual in development mode... 

![screenshot 14](https://user-images.githubusercontent.com/20417498/37650452-c8c9975a-2c56-11e8-8d40-40ca73cf190f.png)

Kindly help if someone knows the issue. Thanks in advance

**Comment by hamza005** [comment]
I've tried using previous version commits but the same issue arises.

**Comment by weiweicui** [comment]
anything in the console log? I think you should apply and set the bing key to the project. This may cause the issue.
https://github.com/weiweicui/PowerBI-Routemap/blob/9c93433620262ba370cf229408abb4d6c16e4ec6/code/lava/bing/controller.ts#L161

**Comment by hamza005** [comment]
There is nothing in the console log. I'll check the controller.ts for bing credentials.

**Comment by hamza005** [comment]
I've used the new bing key generated from the bing account. but the same issue arising. :/

**Comment by hamza005** [comment]
Following is the console after running in powerbi web in development mode:
![screenshot 17](https://user-images.githubusercontent.com/20417498/37758521-53cc5a8c-2dd2-11e8-9d42-0e58e8260bd1.png)

**Comment by weiweicui** [comment]
seems the app.js has an inconsistency, i just patch a little to make it work for the time being. 
please update the code to see if it works?

**Comment by hamza005** [comment]
Thanks! it's working now.
